name: test

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/quality-gate.yml
    with:
      build-number: "0"
      artifact-name: "Saturno.RepoChecker-test"
      upload-artifact: true
      artifact-if-no-files-found: error
